version: '2'
services:
  prometheus:
    build:
      context: prometheus
    container_name: prometheus
    privileged: true
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus.yml
    ports:
      - "9090:9090"
    network_mode: "host"

  node_exporter:
    build:
      context: node_exporter
    container_name: node_exporter
    privileged: true
    ports:
      - "9100:9100"
    volumes:
      - '/proc:/host/proc'
      - '/sys:/host/sys'
      - '/:/rootfs'
      - '/etc/hostname:/etc/host_hostname'
    network_mode: "host"
    command: -collector.procfs /host/proc -collector.sysfs /host/sys -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)"
